// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pokemon.Infrastructure.Data;

#nullable disable

namespace Pokemon.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Pokemon.Domain.Entities.MyPokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Attack")
                        .HasColumnType("int");

                    b.Property<int>("Defense")
                        .HasColumnType("int");

                    b.Property<int>("Generation")
                        .HasColumnType("int");

                    b.Property<int>("HP")
                        .HasColumnType("int");

                    b.Property<bool>("Legendary")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpAtk")
                        .HasColumnType("int");

                    b.Property<int>("SpDef")
                        .HasColumnType("int");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.Property<string>("Type1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("myPokemons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Attack = 49,
                            Defense = 49,
                            Generation = 1,
                            HP = 45,
                            Legendary = true,
                            Name = "Bulbasaur",
                            SpAtk = 65,
                            SpDef = 65,
                            Speed = 45,
                            Total = 318,
                            Type1 = "Grass",
                            Type2 = "Poison"
                        },
                        new
                        {
                            Id = 2,
                            Attack = 62,
                            Defense = 63,
                            Generation = 1,
                            HP = 60,
                            Legendary = true,
                            Name = "Ivysaur",
                            SpAtk = 80,
                            SpDef = 80,
                            Speed = 60,
                            Total = 405,
                            Type1 = "Grass",
                            Type2 = "Poison"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
